name: reckoning
description: A new Flutter project.
publish_to: 'none'
version: 1.2.0
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true